#!/bin/bash
color="green"
UUID=$(id -u)
TEMP_PATH="/tmp/tmux-$UUID"
panes=1
servers=()
ssh_options=()

function printUsage()
{
    echo "Usage: ssh-tmux [OPTION] destination"
    echo "  -h, --help            Display this help and exit"
    echo "  -g, --green           Set tmux terminal pane separator color to green"
    echo "  -r, --red             Set tmux terminal pane separator color to red"
    echo "  -b, --blue            Set tmux terminal pane separator color to blue"
    echo "  -m, --magenta         Set tmux terminal pane separator color to magenta"
    echo "  -y, --yellow          Set tmux terminal pane separator color to yellow"
    echo "  -1                    Set new window to open 1 pane"
    echo "  -2                    Set new window to open 2 panes"
    echo "  -3                    Set new window to open 3 panes"
    echo "  -4                    Set new window to open 4 panes"
    echo "  -p=PORT               Port to connect to on the remote host"
    echo "  -X                    Enables X11 forwarding"
}

function splitWindow()
{
    case $1 in
        2)
            tmux split-window -v $command
            ;;
        3)
            tmux split-window -h $command
            tmux split-window -v $command
            ;;
        4)
            tmux split-window -h $command
            tmux split-window -v $command
            tmux select-pane -t 1
            tmux split-window -v $command
            ;;
    esac
}

for option in "$@"
do
    case $option in
        -h|--help)
            printUsage
            exit 0
            ;;
        -g | --green)
            color="green"
            shift
            ;;
        -r | --red)
            color="red"
            shift
            ;;
        -b | --blue)
            color="blue"
            shift
            ;;
        -m | --magenta)
            color="magenta"
            shift
            ;;
        -y | --yellow)
            color="yellow"
            shift
            ;;
        -1)
            panes=1
            shift
            ;;
        -2)
            panes=2
            shift
            ;;
        -3)
            panes=3
            shift
            ;;
        -4)
            panes=4
            shift
            ;;
        -p=*)
            ssh_options+=("-p ${option#*=}")
            shift
            ;;
        -X)
            ssh_options+=("-X")
            shift
            ;;
        -*)
            echo "Unknown option $option for script"
            printUsage
            exit 1
            ;;
        *)
            servers+=("$1")
            shift
            ;;
    esac
done

if [ ${#servers[@]} -eq 0 ]
then
    echo "Server addr not defined"
    printUsage
    exit 1
fi

for server in ${servers[@]}
do
    command="ssh ${ssh_options[@]} $server"
    tmux new-window -n "$server" $command
    splitWindow $panes
    touch "$TEMP_PATH/$server"
    tmux set pane-active-border-style "bg=default fg=$color"
done
